config/routes.rb
ThreeSeasForum::Application.routes.draw do
  resources :users, :only => [:index, :show]
  resources :posts, :only => [:index, :show]
  resources :topics, :only => [:index, :show]
  resources :forums, :only => [:index, :show]
  resources :search, :only => :index

  match '/faq', :to => 'statics#faq', :as => :faq

  root :to => 'forums#index'
end

app/models/forum.rb
class Forum < ActiveRecord::Base
  attr_accessible :name

  has_many :topics, :dependent => :destroy
  has_many :posts, :through => :topics

  default_scope :order => 'name ASC'
end

app/models/post.rb
class Post < ActiveRecord::Base
  include Tire::Model::Search
  include Tire::Model::Callbacks

  index_name ELASTICSEARCH_INDEX

  mapping do
    indexes :subject, :as => 'subject', :index => :not_analyzed
    indexes :content, :as => proc { |post| ActionController::Base.helpers.strip_tags(post.bbcode) }
    indexes :user_id
  end

  attr_accessible :subject, :text

  belongs_to :user
  belongs_to :topic

  delegate :forum, :to => :topic

  default_scope :order => 'created_at ASC'

  def author
    post_username.blank? ? user.username : post_username
  end

  def bbcode
    text.bbcode_to_html
  end

  def subject
    subject ||= topic.title
  end

end

app/models/rank.rb
class Rank < ActiveRecord::Base
  attr_accessible :title, :min_posts

  has_many :users
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessible :title, :topic_last_post_time

  belongs_to :forum

  has_many :posts, :dependent => :destroy

  default_scope :order => 'topic_last_post_time DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :created_at, :username, :website

  belongs_to :rank

  has_many :posts

  default_scope :order => 'created_at ASC'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  def index
    @forums = Forum.all
  end

  def show
    @forum = Forum.find(params[:id])
    @topics = @forum.topics.paginate(:page => params[:page])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.paginate(:page => params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    search = Tire.search ELASTICSEARCH_INDEX do |s|
      s.query { |q| q.string "content:*#{params[:q]}*" }
      s.highlight :content, :options => { :tag => '<strong class="highlight">' }
      s.size 20
      s.from params[:page] || 1
    end
    @results = search.results
  end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def faq
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.paginate(:page => params[:page])
  end

  def show
    @topic = Topic.find(params[:id])
    @posts = @topic.posts.paginate(:page => params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.paginate(:page => params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(:page => params[:page])
  end
end

app/views/forums/index.html.haml
%ul.nav.nav-tabs.nav-stacked
  - for forum in @forums do
    %li= link_to "#{forum.name} [#{forum.topics.count}](#{forum.posts.count})", forum

app/views/forums/show.html.haml
%ul.breadcrumb
  %li.active= @forum.name

= will_paginate @topics

%ul.nav.nav-tabs.nav-stacked
  - for topic in @topics do
    %li= link_to "#{topic.title} (#{topic.posts.count})", topic

= will_paginate @topics

app/views/layouts/application.html.haml
:erb
  <!DOCTYPE html>
%html
%head
  %title Three Seas Forum
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags
%body
  .container
    .row
      .span6
        %ul.thumbnails
          %li.span6
            = link_to root_path, :class => 'thumbnail' do
              = image_tag 'logo.gif'
      .span6.right
        %h1
          the archives
        %p.lead dusted off in read-only
    .row
      .span6
        %ul.nav.nav-pills
          %li= link_to "Users (#{User.count})", users_path
          %li= link_to "Forums (#{Forum.count})", forums_path
          %li= link_to "Topics (#{Topic.count})", topics_path
          %li= link_to "Posts (#{Post.count})", posts_path
          %li= link_to 'FAQ', faq_path
      .span6
        = form_tag search_index_path, :method => :get, :class => 'form-search pull-right' do
          .input-prepend
            %button.btn{:type => 'submit'} Search
            = text_field_tag 'q', nil, :class => 'span2 search-query', :placeholder => params[:q] ||= 'search...'
    .row
      .span12
        %ul.thumbnails
          %li.span12
            .thumbnail
              .decorator &nbsp;
  .container
    .row
      .span12
        = yield
  .container
    .row
      .span12
        %ul.thumbnails
          %li.span12
            .thumbnail
              .decorator &nbsp;
    .row
      .span6
        %ul.nav.nav-pills
          %li= link_to "Users (#{User.count})", users_path
          %li= link_to "Forums (#{Forum.count})", forums_path
          %li= link_to "Topics (#{Topic.count})", topics_path
          %li= link_to "Posts (#{Post.count})", posts_path
          %li= link_to 'FAQ', faq_path
      .span6
        = form_tag search_index_path, :method => :get, :class => 'form-search pull-right' do
          .input-prepend
            %button.btn{:type => 'submit'} Search
            = text_field_tag 'q', nil, :class => 'span2 search-query', :placeholder => params[:q] ||= 'search...'
    .row
      .span12
        %p.center
          The Three Seas Forum archives are hosted and maintained courtesy of
          = link_to 'Jack Brown', 'https://github.com/brownjohnf'

app/views/posts/_post.html.haml
%h2
  = post.subject
  %small
    posted
    = Time.at(post.created_at).strftime('%d %B %Y')
    in
    = link_to post.forum.name, post.forum
    &rang;
    = link_to post.topic.title, post.topic
    by #{link_to post.author, post.user}, #{post.user.rank.title}
%p
  = raw post.bbcode
  = link_to 'view post', post
%hr

app/views/posts/index.html.haml
= will_paginate

= render @posts

= will_paginate

app/views/posts/show.html.haml
%ul.breadcrumb
  %li
    = link_to @post.forum.name, @post.forum
    %span.divider >
  %li
    = link_to @post.topic.title, @post.topic
    %span.divider >
  %li.active= @post.subject

= render @post

app/views/search/index.html.haml
- if @results.any?
  = will_paginate @results

  %dl
    - @results.each do |result| 
      - user = User.find(result.user_id || 1)
      %dt
        = link_to result.subject, result
        %small
          by
          = link_to user.username, user
          | score
          = result._score
      - for highlight in result.highlight.content do
        %dd= raw '...' + highlight + '...'
      %dd= result.content.truncate(500, :separator => ' ')
      %hr

  = will_paginate @results
- else
  Your search returned no results, or you did not specify a query.

app/views/statics/faq.html.haml
%h1 FAQ

%h2 What was the Three Seas Forum?
%p
  The Three Seas forum was founded back in 2004 by a pair of friends (Wil
  and Sovin Nai) to
  provide a place to discuss the then-fledgling Prince of Nothing series.

%h2 Why can't I post?
%p
  The original forum was taken down a couple years ago because of overwhelming
  spam attacks and a general drop in activity. What you're looking at here is
  the snapshot of the state of forum as of when it was pulled down (with a few
  edits...).

%h2 There's some garbled text in posts... what's with that?
%p
  Because the old forum ran the phpBB platform and used BBCode in its posts,
  but this version is a Ruby/Rails app, there are some formatting bugs. We're
  working on ironing it out. If you find anything grievous, send aengelas a
  message at the Second Apocalypse forum.

app/views/topics/index.html.haml
= will_paginate
%ul.nav.nav-tabs.nav-stacked
  - for topic in @topics do
    %li= link_to "#{topic.title} (#{topic.posts.count})", topic
= will_paginate

app/views/topics/show.html.haml
%ul.breadcrumb
  %li
    = link_to @topic.forum.name, @topic.forum
    %span.divider >
  %li.active= @topic.title

= will_paginate @posts

= render @posts

= will_paginate @posts

app/views/users/index.html.haml
= will_paginate

%ol
  - @users.each do |user|
    %li
      = link_to user.username, user
      |
      = user.posts.count
      posts
      |
      = user.rank.title unless user.rank.nil?

= will_paginate

app/views/users/show.html.haml
%h1
  = @user.username
  %small
    = @user.rank.title unless @user.rank.nil?
    |
    joined
    = Time.at(@user.created_at).strftime('%d %B %Y')
    |
    = @user.posts.count
    posts

%hr

= will_paginate @posts
= render @posts
= will_paginate @posts